services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    ports:
      - "8000:8080"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    command: ["uv", "run", "uvicorn", "main:app", "--ws-ping-interval=2400", "--ws-ping-timeout=60", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    environment:
      - DOCKER_BUILDKIT=1
